[package]
name = "viering-chess-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
vhultman-chess = { git = "https://github.com/inda24PlusPlus/vhultman-chess.git" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
